"""Pydantic data models for GitSentry-AI.

Defines schemas for code review issues, review results, PR synthesis,
and academic benchmark evaluations.
"""

from enum import Enum

from pydantic import BaseModel, Field


class IssueSeverity(str, Enum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    INFO = "INFO"


class IssueCategory(str, Enum):
    SECURITY = "SECURITY"
    DOCUMENTATION = "DOCUMENTATION"
    CODE_SMELL = "CODE_SMELL"
    PERFORMANCE = "PERFORMANCE"
    BEST_PRACTICE = "BEST_PRACTICE"


class MergeRecommendation(str, Enum):
    APPROVE = "APPROVE"
    COMMENT = "COMMENT"
    REQUEST_CHANGES = "REQUEST_CHANGES"


class Issue(BaseModel):
    """Represents a specific code defect or intelligence finding."""

    id: str = Field(description="Unique identifier e.g. SEC-001, DOC-002, SMELL-003")
    file_path: str = Field(description="Relative path of the audited file")
    line_start: int = Field(
        default=1, description="Starting line number of the affected code"
    )
    line_end: int = Field(
        default=1, description="Ending line number of the affected code"
    )
    title: str = Field(description="Concise description of the finding")
    description: str = Field(
        description="Detailed explanation of the flaw or recommendation"
    )
    category: IssueCategory = Field(description="Tri-pillar intelligence category")
    severity: IssueSeverity = Field(description="Risk severity level")
    cwe_id: str | None = Field(
        default=None, description="Common Weakness Enumeration ID e.g. CWE-89, CWE-798"
    )
    cwe_name: str | None = Field(default=None, description="Standard CWE title")
    cvss_score_estimate: float | None = Field(
        default=None,
        ge=0.0,
        le=10.0,
        description="Estimated CVSS v3.1 base score (0.0-10.0)",
    )
    suggested_fix: str | None = Field(
        default=None, description="Concrete replacement code snippet or patch"
    )
    explanation: str | None = Field(
        default=None,
        description="Security/engineering context justifying the recommendation",
    )


class ReviewResult(BaseModel):
    """Comprehensive code review report generated by GitSentry-AI."""

    repo_name: str | None = Field(
        default="Repository", description="Target repository name"
    )
    target_ref: str | None = Field(default="HEAD", description="Commit or PR reference")
    summary: str = Field(
        description="Executive summary of the pull request or diff audit"
    )
    issues: list[Issue] = Field(
        default_factory=list, description="List of detected issues"
    )
    docstring_coverage_pct: float = Field(
        default=100.0,
        ge=0.0,
        le=100.0,
        description="Percentage of changed public APIs/functions documented",
    )
    public_api_changes_count: int = Field(
        default=0, ge=0, description="Total number of modified public functions/classes"
    )
    health_score: int = Field(
        default=100,
        ge=0,
        le=100,
        description="Computed repository health score out of 100",
    )
    risk_assessment: str = Field(
        default="Low Risk", description="Narrative synthesis of deployment risk"
    )
    merge_recommendation: MergeRecommendation = Field(
        default=MergeRecommendation.APPROVE,
        description="Automated gatekeeping recommendation",
    )

    def compute_health_score(self) -> int:
        """Calculate health score based on the academic formula:
        Health Score = max(0, 100 - (25*N_crit + 15*N_high + 8*N_med + 3*N_low))
        """
        n_crit = sum(1 for i in self.issues if i.severity == IssueSeverity.CRITICAL)
        n_high = sum(1 for i in self.issues if i.severity == IssueSeverity.HIGH)
        n_med = sum(1 for i in self.issues if i.severity == IssueSeverity.MEDIUM)
        n_low = sum(1 for i in self.issues if i.severity == IssueSeverity.LOW)

        penalty = (25 * n_crit) + (15 * n_high) + (8 * n_med) + (3 * n_low)
        score = max(0, 100 - penalty)
        self.health_score = score
        return score

    def update_recommendation(self) -> MergeRecommendation:
        """Update merge recommendation based on severity and health score."""
        n_crit = sum(1 for i in self.issues if i.severity == IssueSeverity.CRITICAL)
        n_high = sum(1 for i in self.issues if i.severity == IssueSeverity.HIGH)

        if n_crit > 0 or n_high > 1 or self.health_score < 60:
            self.merge_recommendation = MergeRecommendation.REQUEST_CHANGES
        elif n_high == 1 or len(self.issues) > 0 or self.health_score < 85:
            self.merge_recommendation = MergeRecommendation.COMMENT
        else:
            self.merge_recommendation = MergeRecommendation.APPROVE
        return self.merge_recommendation

    @property
    def critical_count(self) -> int:
        return sum(1 for i in self.issues if i.severity == IssueSeverity.CRITICAL)

    @property
    def high_count(self) -> int:
        return sum(1 for i in self.issues if i.severity == IssueSeverity.HIGH)

    @property
    def medium_count(self) -> int:
        return sum(1 for i in self.issues if i.severity == IssueSeverity.MEDIUM)

    @property
    def low_count(self) -> int:
        return sum(1 for i in self.issues if i.severity == IssueSeverity.LOW)

    @property
    def info_count(self) -> int:
        return sum(1 for i in self.issues if i.severity == IssueSeverity.INFO)

    @property
    def security_issues(self) -> list[Issue]:
        return [i for i in self.issues if i.category == IssueCategory.SECURITY]

    @property
    def doc_issues(self) -> list[Issue]:
        return [i for i in self.issues if i.category == IssueCategory.DOCUMENTATION]

    @property
    def code_smell_issues(self) -> list[Issue]:
        return [i for i in self.issues if i.category == IssueCategory.CODE_SMELL]

    @property
    def performance_issues(self) -> list[Issue]:
        return [i for i in self.issues if i.category == IssueCategory.PERFORMANCE]


class PRDescription(BaseModel):
    """Synthesized Conventional Commit Pull Request description."""

    title: str = Field(
        description="Conventional Commit title e.g. feat(auth): add JWT token refresh"
    )
    summary: str = Field(description="Executive summary of the PR rationale and impact")
    type_of_change: str = Field(
        description="Category of change e.g. Feature, Bugfix, Refactoring, Security Patch"
    )
    scope_and_architecture: str = Field(
        description="Architectural scope and modified system components"
    )
    key_changes: list[str] = Field(
        description="Bullet-point breakdown of key modifications"
    )
    security_considerations: str = Field(
        description="Security implications and countermeasures"
    )
    testing_checklist: list[str] = Field(
        description="Actionable verification items for reviewers"
    )
    breaking_changes: str | None = Field(
        default=None, description="Details of any breaking API changes, or None"
    )

    def to_markdown(self) -> str:
        """Format the PR description as GitHub-ready Markdown."""
        lines = [
            f"# {self.title}",
            "",
            "## 📌 Summary",
            self.summary,
            "",
            "## 🏷️ Type of Change",
            f"- **Type**: {self.type_of_change}",
            "",
            "## 🏗️ Architecture & Scope",
            self.scope_and_architecture,
            "",
            "## 🚀 Key Changes",
        ]
        for change in self.key_changes:
            lines.append(f"- {change}")

        lines.extend(
            [
                "",
                "## 🛡️ Security Considerations",
                self.security_considerations,
                "",
                "## ✅ Testing Checklist",
            ]
        )
        for item in self.testing_checklist:
            lines.append(f"- [ ] {item}")

        if self.breaking_changes:
            lines.extend(["", "## ⚠️ Breaking Changes", self.breaking_changes])

        return "\n".join(lines)


# ---------------- Academic Benchmark Models ---------------- #


class GroundTruthIssue(BaseModel):
    """Expected vulnerability or issue in an academic benchmark sample."""

    file_path: str
    cwe_id: str | None = None
    category: str = "SECURITY"
    severity: str = "HIGH"
    description: str
    line_hint: int | None = None


class GroundTruthSample(BaseModel):
    """Ground-truth annotated diff sample for evaluation."""

    sample_id: str
    file_name: str
    description: str
    expected_issues: list[GroundTruthIssue]
    is_clean: bool = False


class BenchmarkSampleResult(BaseModel):
    """Per-sample benchmark evaluation outcome."""

    sample_id: str
    file_name: str
    true_positives: int
    false_positives: int
    false_negatives: int
    detected_cwe_ids: list[str]
    expected_cwe_ids: list[str]
    status: str  # PASS / PARTIAL / FAIL
    health_score: int
    detection_rate: float


class BenchmarkEvaluationResult(BaseModel):
    """Comprehensive academic evaluation report for GitSentry-AI."""

    total_samples: int
    total_expected_issues: int
    total_detected_issues: int
    total_true_positives: int
    total_false_positives: int
    total_false_negatives: int
    precision: float = Field(description="TP / (TP + FP)")
    recall: float = Field(description="TP / (TP + FN)")
    f1_score: float = Field(description="2 * (P * R) / (P + R)")
    detection_rate: float = Field(description="TP / Total Expected")
    sample_results: list[BenchmarkSampleResult]
    timestamp: str
